### PR TITLE
get hosts for opportunities

### PR DESCRIPTION
**Pull request by ehinson**
https://treetopllc.jira.com/browse/NH-7244

Putting the /nh/users/{user_id}/suggestions/for_logging endpoint into NobleJS

### CODE REVIEW

**Comment by applebya** [comment]
Is there any code on nobleweb to implement this?

**Comment by ehinson** [comment]
Right now this is on gonoble local

**Comment by ehinson** [comment]
@applebya  I'm creating the nw PR right now

**Comment by applebya** [comment]
Ok, if the ticket relates to the nobleweb work (and not the noble.js work) then we need to leave the ticket # out of this ticket's title. Otherwise merging this will close the ticket, which may not be finished yet :+1:"

**Pull request merged**
